export const uiStubs = {
    Button: { template: '<button><slot /></button>' },
    Card: { template: '<div><slot /></div>' },
    CardContent: { template: '<div><slot /></div>' },
    CardHeader: { template: '<div><slot /></div>' },
    CardTitle: { template: '<h1><slot /></h1>' },
    CardDescription: { template: '<p><slot /></p>' },
    CardFooter: { template: '<div><slot /></div>' },
    Separator: { template: '<div />' },
    Badge: { template: '<span><slot /></span>' },
    Input: {
        template: '<input :id="id" :type="type" :placeholder="placeholder" :value="modelValue" @input="$emit(\'update:modelValue\', $event.target.value)" />',
        props: ['id', 'type', 'placeholder', 'modelValue'],
        emits: ['update:modelValue'],
    },
    Label: { template: '<label><slot /></label>' },
    Field: { template: '<div><slot /></div>' },
    FieldGroup: { template: '<div><slot /></div>' },
    FieldLabel: { template: '<label><slot /></label>' },
    FieldDescription: { template: '<p><slot /></p>' },
    FieldSeparator: { template: '<div><slot /></div>' },
    Switch: { template: '<input type="checkbox" />' },
    Dialog: { template: '<div><slot /></div>' },
    DialogContent: { template: '<div><slot /></div>' },
    DialogHeader: { template: '<div><slot /></div>' },
    DialogTitle: { template: '<h2><slot /></h2>' },
    DialogDescription: { template: '<p><slot /></p>' },
    DialogFooter: { template: '<div><slot /></div>' },
    Avatar: { template: '<div><slot /></div>' },
    AvatarImage: { template: '<img />' },
    AvatarFallback: { template: '<div><slot /></div>' },
    ResizablePanelGroup: { template: '<div><slot /></div>' },
    ResizablePanel: { template: '<div><slot /></div>' },
    ResizableHandle: { template: '<div />' },
    JsonTreeNode: { template: '<div />' },
    RouterLink: { template: '<a><slot /></a>' },
    Server: { template: '<span />' },
}
